# Generated by Django 4.2.1 on 2023-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='vendor/')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
