# Generated by Django 4.2.1 on 2023-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='vendor',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_mobile',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
