# Generated by Django 4.2.1 on 2023-09-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '6. Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3. Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': '4. Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': '5. Sales'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '2. Units'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '1. Vendors'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='pur_date',
            new_name='purchase_date',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.purchase'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_qty',
            field=models.FloatField(default=0, null=True),
        ),
    ]
