# Generated by Django 4.2.1 on 2023-09-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sale_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_mobile', models.CharField(default=None, max_length=12)),
                ('customer_address', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_mobile',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
