# Generated by Django 4.2.1 on 2023-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_remove_sale_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7. Customers'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='photo',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
